; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[common]
build_flags =
    -std=gnu++17
    -Wall
    -Wextra

[debug]
build_flags =
    ${common.build_flags}
    -Og

[release]
build_flags =
    ${common.build_flags}
    -Os

[exp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf

upload_speed = 460800
monitor_speed = 115200

sdkconfig_overrides =
    CONFIG_COMPILER_CXX_STANDARD=gnu++17
    CONFIG_COMPILER_CXX_EXCEPTIONS=0
    CONFIG_COMPILER_CXX_RTTI=0

    ; USB serial logging
    CONFIG_ESP_CONSOLE_USB_CDC=y
    CONFIG_USB_CDC_ENABLED=y

[env]
; Make sure defaults will not override necessary flags
build_unflags = 
    -std=gnu++11
    -std=c++11
lib_ldf_mode = chain+

[env:esp32-c3-dev]
extends = exp32-c3
build_flags = ${debug.build_flags}
monitor_filters = esp32_exception_decoder

[env:esp32-c3-release]
extends = exp32-c3
build_flags = ${release.build_flags}

[env:host_test]
platform = native

test_framework = unity
test_filter = test_host
test_build_src = yes

build_src_filter = +<*> -<main.cpp>
build_flags = 
    ${debug.build_flags}
    -DHOST_TEST
    -I.pio/build/host_test/unity_config
    -fexceptions
    -frtti

lib_deps = throwtheswitch/Unity@^2.6.0
    