; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200

; Make sure defaults will not override necessary flags
build_unflags = 
    -std=gnu++11
    -std=c++11

build_flags = 
    -Og           ; Debug optimization
    -Wall -Wextra ; Strict warnings

board_build.esp-idf.sdkconfig_append =
    CONFIG_COMPILER_CXX_STANDARD=gnu++17
    CONFIG_COMPILER_CXX_EXCEPTIONS=0
    CONFIG_COMPILER_CXX_RTTI=0

    ; USB serial logging
    CONFIG_ESP_CONSOLE_USB_CDC=y
    CONFIG_USB_CDC_ENABLED=y

